name: Cypress Test

on:
#  push:
#    branches:
#      - 'master'
  workflow_dispatch:

jobs:
  project-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Project build
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          build: yarn install

      - name: Save build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./
          if-no-files-found: error

  project-linter:
    runs-on: ubuntu-latest
    needs: project-build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Linter code check
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          start: yarn linter:code:check

  project-report-specs:
    runs-on: ubuntu-latest
    needs: project-linter
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Report Specs
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          start: yarn find:specs:name

  project-runt-tests:
    runs-on: ubuntu-latest
    needs: project-linter
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Run tests
        uses: cypress-io/github-action@v6
        with:
          start: yarn cy:run
