name: Cypress Test

on:
#  push:
#    branches:
#      - 'master'
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Project build
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          useLockFile: false
          build: yarn install

      - name: Save build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          if-no-files-found: error
          path: build

  cypress-test-report:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Run tests
        uses: cypress-io/github-action@v6
        with:
          start: yarn find:specs:name
