name: Cypress Test

on:
#  push:
#    branches:
#      - 'master'
  workflow_dispatch:

jobs:
  project-execute-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Project install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
        
      - name: Linter code check
        run: yarn linter:code:check

      - name: Report specs
        run: yarn find:specs:name

      - name: Run tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          command: yarn cy:run
